import esbuild from "esbuild"
import process from "node:process"
import path from "node:path"
import { spawn } from "node:child_process"
import { builtinModules } from "node:module"

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`

const prod = process.argv[2] === "production"
const builtinExternal = [...builtinModules, ...builtinModules.map(m => `node:${m}`)]
const external = [
  "electron",
  "@electron/remote",
  "@electron/remote/main",
  "@trevoreyre/autocomplete-js",
  "fs-walk",
  "music-metadata",
  "smooth-dnd",
  ...builtinExternal
]

const electronBinary = path.join(
  process.cwd(),
  "node_modules",
  ".bin",
  process.platform === "win32" ? "electron.cmd" : "electron"
)

let electronProcess = null
let shouldRestartElectron = false

function startElectron() {
  electronProcess = spawn(electronBinary, ["."], {
    stdio: "inherit",
    env: { ...process.env, NODE_OPTIONS: "--experimental-sqlite" }
  })

  electronProcess.on("exit", () => {
    const restart = shouldRestartElectron
    shouldRestartElectron = false
    electronProcess = null
    if (restart) {
      startElectron()
    }
  })
}

function restartElectron() {
  if (!electronProcess) {
    startElectron()
    return
  }
  shouldRestartElectron = true
  electronProcess.kill()
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: {
    main: "src/main.ts",
    preload: "src/preload.ts"
  },
  bundle: true,
  external,
  platform: "node",
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "src",
  plugins: prod
    ? []
    : [{
        name: "electron-reloader",
        setup(build) {
          build.onEnd(result => {
            if (result.errors.length === 0) {
              restartElectron()
            }
          })
        }
      }]
})

if (prod) {
  await context.rebuild()
  await context.dispose()
  process.exit(0)
}

await context.watch()

async function shutdown() {
  await context.dispose()
  if (electronProcess) {
    electronProcess.kill()
  }
  process.exit(0)
}

process.on("SIGINT", () => {
  void shutdown()
})

process.on("SIGTERM", () => {
  void shutdown()
})
